namespace RandomVideoPlayer.Model
{
    public static class LanguageCodesISO639
    {
        //Everything Everywhere All at Once
        public static Dictionary<string, string> LanguageMap = new Dictionary<string, string>
        {
           { "aar", "Afar" },
           { "abk", "Abkhazian" },
           { "ace", "Achinese" },
           { "ach", "Acoli" },
           { "ada", "Adangme" },
           { "ady", "Adyghe" },
           { "afa", "Afro-Asiatic Languages" },
           { "afh", "Afrihili" },
           { "afr", "Afrikaans" },
           { "ain", "Ainu" },
           { "aka", "Akan" },
           { "akk", "Akkadian" },
           { "alb", "Albanian" },
           { "ale", "Aleut" },
           { "alg", "Algonquian Languages" },
           { "alt", "Southern Altai" },
           { "amh", "Amharic" },
           { "ang", "Old English" },
           { "anp", "Angika" },
           { "apa", "Apache Languages" },
           { "ara", "Arabic" },
           { "arc", "Official Aramaic (700-300 BCE)" },
           { "arg", "Aragonese" },
           { "arm", "Armenian" },
           { "arn", "Mapudungun" },
           { "arp", "Arapaho" },
           { "art", "Artificial Languages" },
           { "arw", "Arawak" },
           { "asm", "Assamese" },
           { "ast", "Asturian" },
           { "ath", "Athapascan Languages" },
           { "aus", "Australian Languages" },
           { "ava", "Avaric" },
           { "ave", "Avestan" },
           { "awa", "Awadhi" },
           { "aym", "Aymara" },
           { "aze", "Azerbaijani" },
           { "bad", "Banda Languages" },
           { "bai", "Bamileke Languages" },
           { "bak", "Bashkir" },
           { "bal", "Baluchi" },
           { "bam", "Bambara" },
           { "ban", "Balinese" },
           { "baq", "Basque" },
           { "bas", "Basaa" },
           { "bat", "Baltic Languages" },
           { "bej", "Beja" },
           { "bel", "Belarusian" },
           { "bem", "Bemba" },
           { "ben", "Bengali" },
           { "ber", "Berber Languages" },
           { "bho", "Bhojpuri" },
           { "bih", "Bihari Languages" },
           { "bik", "Bikol" },
           { "bin", "Bini" },
           { "bis", "Bislama" },
           { "bla", "Siksika" },
           { "bnt", "Bantu Languages" },
           { "bos", "Bosnian" },
           { "bra", "Braj" },
           { "bre", "Breton" },
           { "btk", "Batak Languages" },
           { "bua", "Buriat" },
           { "bug", "Buginese" },
           { "bul", "Bulgarian" },
           { "bur", "Burmese" },
           { "byn", "Blin" },
           { "cad", "Caddo" },
           { "cai", "Central American Indian Languages" },
           { "car", "Galibi Carib" },
           { "cat", "Catalan" },
           { "cau", "Caucasian Languages" },
           { "ceb", "Cebuano" },
           { "cel", "Celtic Languages" },
           { "cha", "Chamorro" },
           { "chb", "Chibcha" },
           { "che", "Chechen" },
           { "chg", "Chagatai" },
           { "chi", "Chinese" },
           { "chk", "Chuukese" },
           { "chm", "Mari" },
           { "chn", "Chinook Jargon" },
           { "cho", "Choctaw" },
           { "chp", "Chipewyan" },
           { "chr", "Cherokee" },
           { "chu", "Church Slavic" },
           { "chv", "Chuvash" },
           { "chy", "Cheyenne" },
           { "cmc", "Chamic Languages" },
           { "cop", "Coptic" },
           { "cor", "Cornish" },
           { "cos", "Corsican" },
           { "cpe", "Creoles and Pidgins, English-based" },
           { "cpf", "Creoles and Pidgins, French-based" },
           { "cpp", "Creoles and Pidgins, Portuguese-based" },
           { "cre", "Cree" },
           { "crh", "Crimean Tatar" },
           { "crp", "Creoles and Pidgins" },
           { "csb", "Kashubian" },
           { "cus", "Cushitic Languages" },
           { "cze", "Czech" },
           { "dak", "Dakota" },
           { "dan", "Danish" },
           { "dar", "Dargwa" },
           { "day", "Dayak" },
           { "del", "Delaware" },
           { "den", "Slave (Athapascan)" },
           { "dgr", "Dogrib" },
           { "din", "Dinka" },
           { "div", "Divehi" },
           { "doi", "Dogri" },
           { "dra", "Dravidian Languages" },
           { "dsb", "Lower Sorbian" },
           { "dua", "Duala" },
           { "dum", "Middle Dutch" },
           { "dut", "Dutch" },
           { "dyu", "Dyula" },
           { "dzo", "Dzongkha" },
           { "efi", "Efik" },
           { "egy", "Ancient Egyptian" },
           { "eka", "Ekajuk" },
           { "elx", "Elamite" },
           { "eng", "English" },
           { "enm", "Middle English" },
           { "epo", "Esperanto" },
           { "est", "Estonian" },
           { "ewe", "Ewe" },
           { "ewo", "Ewondo" },
           { "fan", "Fang" },
           { "fao", "Faroese" },
           { "fat", "Fanti" },
           { "fij", "Fijian" },
           { "fil", "Filipino" },
           { "fin", "Finnish" },
           { "fiu", "Finno-Ugrian Languages" },
           { "fon", "Fon" },
           { "fre", "French" },
           { "frm", "Middle French" },
           { "fro", "Old French" },
           { "frr", "Northern Frisian" },
           { "frs", "Eastern Frisian" },
           { "fry", "Western Frisian" },
           { "ful", "Fulah" },
           { "fur", "Friulian" },
           { "gaa", "Ga" },
           { "gay", "Gayo" },
           { "gba", "Gbaya" },
           { "gem", "Germanic Languages" },
           { "geo", "Georgian" },
           { "ger", "German" },
           { "gez", "Geez" },
           { "gil", "Gilbertese" },
           { "gla", "Scottish Gaelic" },
           { "gle", "Irish" },
           { "glg", "Galician" },
           { "glv", "Manx" },
           { "gon", "Gondi" },
           { "gor", "Gorontalo" },
           { "got", "Gothic" },
           { "grb", "Grebo" },
           { "grc", "Ancient Greek" },
           { "gre", "Greek, Modern" },
           { "grn", "Guarani" },
           { "gsw", "Swiss German" },
           { "guj", "Gujarati" },
           { "gwi", "Gwichʼin" },
           { "hai", "Haida" },
           { "hat", "Haitian" },
           { "hau", "Hausa" },
           { "haw", "Hawaiian" },
           { "heb", "Hebrew" },
           { "her", "Herero" },
           { "hil", "Hiligaynon" },
           { "him", "Himachali Languages" },
           { "hin", "Hindi" },
           { "hit", "Hittite" },
           { "hmn", "Hmong" },
           { "hmo", "Hiri Motu" },
           { "hrv", "Croatian" },
           { "hsb", "Upper Sorbian" },
           { "hun", "Hungarian" },
           { "hup", "Hupa" },
           { "iba", "Iban" },
           { "ibo", "Igbo" },
           { "ice", "Icelandic" },
           { "ido", "Ido" },
           { "iii", "Sichuan Yi" },
           { "ijo", "Ijo Languages" },
           { "iku", "Inuktitut" },
           { "ile", "Interlingue" },
           { "ilo", "Iloko" },
           { "ina", "Interlingua (International Auxiliary Language Association)" },
           { "inc", "Indic Languages" },
           { "ind", "Indonesian" },
           { "ine", "Indo-European Languages" },
           { "inh", "Ingush" },
           { "ipk", "Inupiaq" },
           { "ira", "Iranian Languages" },
           { "iro", "Iroquoian Languages" },
           { "ita", "Italian" },
           { "jav", "Javanese" },
           { "jbo", "Lojban" },
           { "jpn", "Japanese" },
           { "jpr", "Judeo-Persian" },
           { "jrb", "Judeo-Arabic" },
           { "kaa", "Kara-Kalpak" },
           { "kab", "Kabyle" },
           { "kac", "Kachin" },
           { "kal", "Kalaallisut" },
           { "kam", "Kamba" },
           { "kan", "Kannada" },
           { "kar", "Karen Languages" },
           { "kas", "Kashmiri" },
           { "kau", "Kanuri" },
           { "kaw", "Kawi" },
           { "kaz", "Kazakh" },
           { "kbd", "Kabardian" },
           { "kha", "Khasi" },
           { "khi", "Khoisan Languages" },
           { "khm", "Khmer" },
           { "kho", "Khotanese" },
           { "kik", "Kikuyu" },
           { "kin", "Kinyarwanda" },
           { "kir", "Kyrgyz" },
           { "kmb", "Kimbundu" },
           { "kok", "Konkani" },
           { "kom", "Komi" },
           { "kon", "Kongo" },
           { "kor", "Korean" },
           { "kos", "Kosraean" },
           { "kpe", "Kpelle" },
           { "krc", "Karachay-Balkar" },
           { "krl", "Karelian" },
           { "kro", "Kru Languages" },
           { "kru", "Kurukh" },
           { "kua", "Kuanyama" },
           { "kum", "Kumyk" },
           { "kur", "Kurdish" },
           { "kut", "Kutenai" },
           { "lad", "Ladino" },
           { "lah", "Lahnda" },
           { "lam", "Lamba" },
           { "lao", "Lao" },
           { "lat", "Latin" },
           { "lav", "Latvian" },
           { "lez", "Lezghian" },
           { "lim", "Limburgan" },
           { "lin", "Lingala" },
           { "lit", "Lithuanian" },
           { "lol", "Mongo" },
           { "loz", "Lozi" },
           { "ltz", "Luxembourgish" },
           { "lua", "Luba-Lulua" },
           { "lub", "Luba-Katanga" },
           { "lug", "Ganda" },
           { "lui", "Luiseno" },
           { "lun", "Lunda" },
           { "luo", "Luo (Kenya and Tanzania)" },
           { "lus", "Lushai" },
           { "mac", "Macedonian" },
           { "mad", "Madurese" },
           { "mag", "Magahi" },
           { "mah", "Marshallese" },
           { "mai", "Maithili" },
           { "mak", "Makasar" },
           { "mal", "Malayalam" },
           { "man", "Mandingo" },
           { "mao", "Maori" },
           { "map", "Austronesian Languages" },
           { "mar", "Marathi" },
           { "mas", "Masai" },
           { "may", "Malay" },
           { "mdf", "Moksha" },
           { "mdr", "Mandar" },
           { "men", "Mende" },
           { "mga", "Middle Irish" },
           { "mic", "Mi'kmaq" },
           { "min", "Minangkabau" },
           { "mis", "Uncoded Languages" },
           { "mkh", "Mon-Khmer Languages" },
           { "mlg", "Malagasy" },
           { "mlt", "Maltese" },
           { "mnc", "Manchu" },
           { "mni", "Manipuri" },
           { "mno", "Manobo Languages" },
           { "moh", "Mohawk" },
           { "mol", "Moldavian" },
           { "mon", "Mongolian" },
           { "mos", "Mossi" },
           { "mul", "Multiple Languages" },
           { "mun", "Munda Languages" },
           { "mus", "Creek" },
           { "mwl", "Mirandese" },
           { "mwr", "Marwari" },
           { "myn", "Mayan Languages" },
           { "myv", "Erzya" },
           { "nah", "Nahuatl Languages" },
           { "nai", "North American Indian Languages" },
           { "nap", "Neapolitan" },
           { "nau", "Nauru" },
           { "nav", "Navajo" },
           { "nbl", "South Ndebele" },
           { "nde", "North Ndebele" },
           { "ndo", "Ndonga" },
           { "nds", "Low German" },
           { "nep", "Nepali" },
           { "new", "Newari" },
           { "nia", "Nias" },
           { "nic", "Niger-Kordofanian Languages" },
           { "niu", "Niuean" },
           { "nno", "Norwegian (nno)" },
           { "nob", "Norwegian (nob)" },
           { "nog", "Nogai" },
           { "non", "Old Norse" },
           { "nor", "Norwegian (nor)" },
           { "nqo", "N'Ko" },
           { "nso", "Northern Sotho" },
           { "nub", "Nubian Languages" },
           { "nwc", "Classical Newari" },
           { "nya", "Chichewa" },
           { "nym", "Nyamwezi" },
           { "nyn", "Nyankole" },
           { "nyo", "Nyoro" },
           { "nzi", "Nzima" },
           { "oci", "Occitan" },
           { "oji", "Ojibwa" },
           { "ori", "Oriya" },
           { "orm", "Oromo" },
           { "osa", "Osage" },
           { "oss", "Ossetian" },
           { "ota", "Ottoman Turkish" },
           { "oto", "Otomian Languages" },
           { "paa", "Papuan Languages" },
           { "pag", "Pangasinan" },
           { "pal", "Pahlavi" },
           { "pam", "Pampanga" },
           { "pan", "Punjabi" },
           { "pap", "Papiamento" },
           { "pau", "Palauan" },
           { "peo", "Old Persian" },
           { "per", "Persian" },
           { "phi", "Philippine Languages" },
           { "phn", "Phoenician" },
           { "pli", "Pali" },
           { "pol", "Polish" },
           { "pon", "Pohnpeian" },
           { "por", "Portuguese" },
           { "pra", "Prakrit Languages" },
           { "pro", "Old Provençal" },
           { "pus", "Pushto" },
           { "que", "Quechua" },
           { "raj", "Rajasthani" },
           { "rap", "Rapanui" },
           { "rar", "Rarotongan" },
           { "roa", "Romance Languages" },
           { "roh", "Romansh" },
           { "rom", "Romany" },
           { "rum", "Romanian" },
           { "run", "Rundi" },
           { "rup", "Aromanian" },
           { "rus", "Russian" },
           { "sad", "Sandawe" },
           { "sag", "Sango" },
           { "sah", "Yakut" },
           { "sai", "South American Indian Languages" },
           { "sal", "Salishan Languages" },
           { "sam", "Samaritan Aramaic" },
           { "san", "Sanskrit" },
           { "sas", "Sasak" },
           { "sat", "Santali" },
           { "scn", "Sicilian" },
           { "sco", "Scots" },
           { "sel", "Selkup" },
           { "sem", "Semitic Languages" },
           { "sga", "Old Irish" },
           { "sgn", "Sign Languages" },
           { "shn", "Shan" },
           { "sid", "Sidamo" },
           { "sin", "Sinhala" },
           { "sio", "Siouan Languages" },
           { "sit", "Sino-Tibetan Languages" },
           { "sla", "Slavic Languages" },
           { "slo", "Slovak" },
           { "slv", "Slovenian" },
           { "sma", "Southern Sami" },
           { "sme", "Northern Sami" },
           { "smi", "Sami Languages" },
           { "smj", "Lule Sami" },
           { "smn", "Inari Sami" },
           { "smo", "Samoan" },
           { "sms", "Skolt Sami" },
           { "sna", "Shona" },
           { "snd", "Sindhi" },
           { "snk", "Soninke" },
           { "sog", "Sogdian" },
           { "som", "Somali" },
           { "son", "Songhai Languages" },
           { "sot", "Sotho" },
           { "spa", "Spanish" },
           { "srd", "Sardinian" },
           { "srn", "Sranan Tongo" },
           { "srp", "Serbian" },
           { "srr", "Serer" },
           { "ssa", "Nilo-Saharan Languages" },
           { "ssw", "Swati" },
           { "suk", "Sukuma" },
           { "sun", "Sundanese" },
           { "sus", "Susu" },
           { "sux", "Sumerian" },
           { "swa", "Swahili" },
           { "swe", "Swedish" },
           { "syc", "Classical Syriac" },
           { "syr", "Syriac" },
           { "tah", "Tahitian" },
           { "tai", "Tai Languages" },
           { "tam", "Tamil" },
           { "tat", "Tatar" },
           { "tel", "Telugu" },
           { "tem", "Timne" },
           { "ter", "Tereno" },
           { "tet", "Tetum" },
           { "tgk", "Tajik" },
           { "tgl", "Tagalog" },
           { "tha", "Thai" },
           { "tib", "Tibetan" },
           { "tig", "Tigre" },
           { "tir", "Tigrinya" },
           { "tiv", "Tiv" },
           { "tkl", "Tokelau" },
           { "tlh", "Klingon" },
           { "tli", "Tlingit" },
           { "tmh", "Tamashek" },
           { "tog", "Tonga (Nyasa)" },
           { "ton", "Tonga (Tonga Islands)" },
           { "tpi", "Tok Pisin" },
           { "tsi", "Tsimshian" },
           { "tsn", "Tswana" },
           { "tso", "Tsonga" },
           { "tuk", "Turkmen" },
           { "tum", "Tumbuka" },
           { "tup", "Tupi Languages" },
           { "tur", "Turkish" },
           { "tut", "Altaic Languages" },
           { "tvl", "Tuvalu" },
           { "twi", "Twi" },
           { "tyv", "Tuvinian" },
           { "udm", "Udmurt" },
           { "uga", "Ugaritic" },
           { "uig", "Uighur" },
           { "ukr", "Ukrainian" },
           { "umb", "Umbundu" },
           { "und", "Undetermined" },
           { "urd", "Urdu" },
           { "uzb", "Uzbek" },
           { "vai", "Vai" },
           { "ven", "Venda" },
           { "vie", "Vietnamese" },
           { "vol", "Volapük" },
           { "vot", "Votic" },
           { "wak", "Wakashan Languages" },
           { "wal", "Wolaitta" },
           { "war", "Waray" },
           { "was", "Washo" },
           { "wel", "Welsh" },
           { "wen", "Sorbian Languages" },
           { "wln", "Walloon" },
           { "wol", "Wolof" },
           { "xal", "Kalmyk" },
           { "xho", "Xhosa" },
           { "yao", "Yao" },
           { "yap", "Yapese" },
           { "yid", "Yiddish" },
           { "yor", "Yoruba" },
           { "ypk", "Yupik Languages" },
           { "zap", "Zapotec" },
           { "zen", "Zenaga" },
           { "zgh", "Standard Moroccan Tamazight" },
           { "zha", "Zhuang" },
           { "znd", "Zande Languages" },
           { "zul", "Zulu" },
           { "zun", "Zuni" }
        };

    }
}
